locale = 'en-us'
title = 'Openpresso'
theme = ['hugo-admonitions', 'PaperMod']

[params]
    disableThemeToggle = false
    ShowShareButtons = false
    ShowReadingTime = false
    label = { icon = "/logo.svg", iconHeight = "64" }

    [params.assets]
        favicon = "/favicon.ico"
        favicon16x16 = "/favicon-16x16.png"
        favicon32x32 = "/favicon-32x32.png"
        apple_touch_icon = "/apple-touch-icon.png"

[menu]
    [[menu.main]]
        identifier = "subprojects"
        name = "Subprojects"
        url = "/subprojects/"
        weight = 10
    [[menu.main]]
        identifier = "roadmap"
        name = "Roadmap"
        url = "/roadmap/"
        weight = 20

