name: Build and Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build static website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.163.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: openpresso-website
          path: public

  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ github.repository == 'openpresso/openpresso-website' }}
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v8
        with:
          name: openpresso-website
          path: ./website

      - name: Deploy website
        uses: openpresso/openpresso.github.io/.github/actions/deploy-site@gh-pages
        with:
          commit_message: "[CI] Openpresso website deployed: ${{ github.event.head_commit.message }}"
          repository: openpresso/openpresso.github.io
          deployment_key: ${{ secrets.PAGES_DEPLOY_KEY }}
          source_dir: ./website
          checkout_path: pages
